//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public string ClientNo { get; set; }
        public Nullable<int> Data { get; set; }
        public Nullable<int> DataNumber { get; set; }
        public string timestamp { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public int PrimKey { get; set; }
    }
}
